version: '3'

services:
  api:
    container_name: 156-api
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    container_name: 156-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: chame156
      MYSQL_DATABASE: chame156
    ports:
      - 3306:3306