version: '3'

services:
  api:
    container_name: 156-api
    build: .
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    links:
      - db
    depends_on:
      - db

  db:
    container_name: 156-db
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: chame156
      POSTGRES_DB: chame156
    ports:
      - 5432:5432

  # mysql:
  #   container_name: 156-mysql
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: chame156
  #     MYSQL_DATABASE: chame156
  #   ports:
  #     - 3306:3306